[package]
name = "blog_os"
version = "0.1.0"
edition = "2018"

[dependencies]
bootloader = "0.9"
volatile = "0.2.6"

# Let's prevent default stack unwinding when panic occurs, rather let it abort
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
