# allows to recompile `core` and other standard library crates on demand, instead of using the precompiled
# versions shipped with the Rust installation.

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
# tells `cargo` to use our `x86_64-blog_os.json` target when no explicit `--target` arg is passed
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
